-- MySQL Script generated by MySQL Workbench
-- Sun Feb 27 13:50:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exo205
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exo205
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exo205` DEFAULT CHARACTER SET utf8 ;
USE `exo205` ;

-- -----------------------------------------------------
-- Table `exo205`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo205`.`client` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `username` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `register_date` DATETIME NOT NULL,
    `last_activity` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo205`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo205`.`user` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `username` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exo205`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exo205`.`admin` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `username` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
